## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix is a function that generates a list of four functions that:
#   1- Set: caches a matrix
#   2- Get: returns the matrix cached
#   3- setinv: caches the inverse of the matrix
#   4- getinv: returns the cached inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) {
        x <<- y                                     # Caching matrix
        i <<- NULL                                  # Reseting the elemnt that holds the inverse
    }
    
    get <- function() {
        x                                           # Returns the cached matrix
    }
    setinv <- function(solve) {
        i <<- solve                                 # Cahes the inverse of the matrix using the solve() function
    }
    getinv <- function() {
        i                                           # Returns the cached inverse
    }
    
    list(set = set,                                 # Creates the list of functions and names them accordingly
         get = get,
         setinv = setinv,
         getinv = getinv)
}


## cacheSolve returns the inverse of the matrix cached in makeCacheMatrix, if no inverse matrix is cached, then solve() will be run on the original
## cached matrix in order to get its inverse. If an inverse matrix is already cached (because cacheSolve() was already run on the list generated by 
## makeCacheMatrix) then this cached inverse is returned avoiding costly computations involved in solve().

cacheSolve <- function(x, ...) {
    i <- x$getinv()                                 # gets the inverse matrix cached 
    if(!is.null(i)) {                               # if there is a cached inverse matrix then ...
        message("getting cached inverse matrix")
        return(i)                                   # returns the cached matrix
    } else {                                        # if there is not a cached inverse matrix then ...
        data <- x$get()                             # gets the original cached matrix
        i <- solve(data, ...)                       # runs solve() to get the inverse matrix
        x$setinv(i)                                 # caches the inverse matrix
        i                                           # Return a matrix that is the inverse of the matrix cached in makeCacheMatrix()
    }
}
